Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TraitorsMicroSite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TraitorsMicroSite.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TraitorsMicroSite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/RedirectToGingerFox.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading;

namespace TraitorsMicroSite.Pages
{
    public class RedirectToGingerFoxModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Shared/Components/CookieConsent/CookieConsentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;



namespace GingerFoxHub.Pages.Shared.Components.CookieConsent
{
    public class CookieConsentViewComponent : ViewComponent
    {
        public class CookieConsentData
        {
            public string Name { get; set; }
        }


        public IList<CookieConsentData> cookieList = new List<CookieConsentData>();
        public IViewComponentResult Invoke(string TrackingCookieNames)
        {

            //var CookieConsentTracking = HttpContext.Request.Cookies["CookieConsentTracking"];
            //var CookieConsent = HttpContext.Request.Cookies["CookieConsent"];
            //if (CookieConsent == "true")
            //{
            //    SessionHelper.SetObjectAsJson(HttpContext.Session, "CookieConsent", "true");
            //}
            //else
            //{
            //    SessionHelper.SetObjectAsJson(HttpContext.Session, "CookieConsent", "false");
            //}
            //if (CookieConsentTracking == "true")
            //{
            //    SessionHelper.SetObjectAsJson(HttpContext.Session, "CookieConsentTracking", "true");
            //}
            //else
            //{
            //    SessionHelper.SetObjectAsJson(HttpContext.Session, "CookieConsentTracking", "false");
            //}




            var ListOfCookies = TrackingCookieNames.Split(",");
            foreach (var cookie in ListOfCookies)
            {
                CookieConsentData cookieData = new CookieConsentData();
                cookieData.Name = cookie;
                cookieList.Add(cookieData);
            }



            return View("CookieConsent", cookieList);
        }


    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Homepage";
    Layout = "_TraitorsLayout";
    string ImageServerURL = "https://media.gingerfox.co.uk/TraitorsMicroSite";
}
<link href="~/css/index.css" rel="stylesheet" asp-append-version="true"/>

<div class="bannerContainer">
    <div class="h1BannerContainer">
        <h1 class="bannerH1">A GAME OF TRUST AND TREACHERY...</h1>
    </div>
    <div class="h2BannerContainer">
        <h2 class="bannerH2">DO YOU HAVE WHAT IT TAKES TO PLAY?</h2>
    </div>
    
    <img class="desktopVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_WEB_1.jpg" />
    <img class="mobileVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_MOB_1.jpg" />
    <a id="BuyNowBtnBanner" class="BuyNowBtn"><div id="ProductPrice"></div>Buy Now</a>
</div>


@*<div class="reviewBanner">
    <div class="starContainer">
        <img src="@ImageServerURL/WWTBAM_STAR_WHITE.png" />
        <img src="@ImageServerURL/WWTBAM_STAR_WHITE.png" />
        <img src="@ImageServerURL/WWTBAM_STAR_WHITE.png" />
        <img src="@ImageServerURL/WWTBAM_STAR_WHITE.png" />
        <img src="@ImageServerURL/WWTBAM_STAR_WHITE.png" />
    </div>
    <p class="desktopVersion">(89 Reviews)</p>
    <p class="reviewMobileText mobileVersion">RATED 5 STARS ON AMAZON FROM 89 REVIEWS</p>
</div>*@
<div id="InTheBox" class="InTheBoxContainer">
   
    <div class="InTheBoxInfoContainer container">
         <div class="boxContentsContainer">
            <h2>What's In The Box?</h2>
            <p>The Traitors Card Game Box Includes:</p>
            <ul>
                <li>40 Gold Coin Cards,</li>
                <li>27 Action Cards,</li>
                <li>12 Night Cards,</li>
                <li>6 Traitor's Dilemma Cards,</li>
                <li>Rules Booklet.</li>
            </ul>
        </div>
        <img class="desktopVersion" src="@ImageServerURL/WHATS_IN_THE_BOX_WEB.jpg" />
        <img class="mobileVersion" src="@ImageServerURL/WHATS_IN_THE_BOX_MOB.jpg" />
       

    </div>
</div>

<div id="Details" class="detailsContainer">
    <div class="desktopVersion">

        <div class="ScaleableDetails">
            <p><nobr>Trust no one in this darkly dramatic family game. Players work together to</nobr></p>
            <p><nobr>collect a hoard of golden treasure, but danger is lurking. Among you are</nobr></p>
            <p><nobr>Traitors - and every time Night falls there's a good chance someone will</nobr></p>
            <p><nobr>attempt to commit a murder under the cover of darkness.</nobr></p>
        </div>
       
    </div>
    <div class="mobileVersion">
        <div class="ScaleableDetails">
            <p><nobr>Trust no one in this darkly</nobr></p>
            <p><nobr>dramatic family game. Players</nobr></p>
            <p><nobr>work together to collect a hoard</nobr></p>
            <p><nobr>of golden treasure, but danger is</nobr></p>
            <p><nobr>lurking. Among you are Traitors -</nobr></p>
            <p><nobr>and every time Night falls there's </nobr></p>
            <p><nobr>a good chance someone will</nobr></p>
            <p><nobr>attempt to commit a murder</nobr></p>
            <p><nobr>under the cover of darkness.</nobr></p>
            
        </div>
    </div>
    
    <img class="desktopVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_WEB_2.jpg" />
    <img class="mobileVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_MOB_2.png" />
</div>

<div id="HowToPlay" class="VideoContainer">
    <h4>How To Play</h4>
  
    <div class="YTContainer">
        <div id="player"></div>
    </div>
    
</div>
<div class="MidBanner">
    <img class="mobileVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_MOB_3.jpg" />
    <img class="desktopVersion" src="@ImageServerURL/GFHUB_TRAITORS_BANNER_WEB_3.jpg" />
</div>
<div class="RTBFUContainer">
    <h4>WHY BUY FROM US</h4>
    <div class="cardContainer">
        <img class="desktopVersion" src="@ImageServerURL/WHY_BUY_FROM_US_WEB.png" />
        <img class="mobileVersion" src="@ImageServerURL/WHY_BUY_FROM_US_MOB.png" />
    </div>
</div>
<div id="FAQs" class="LifeStyleContainer">
    <link href="~/lib/owlcarousel2/assets/owl.carousel.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/owlcarousel2/assets/owl.theme.default.min.css" rel="stylesheet" asp-append-version="true" />
    <script src="~/lib/owlcarousel2/owl.carousel.min.js" asp-append-version="true"></script>
    <div class="owl-carousel">
        <div><img class="lifeStyleImg" src="@ImageServerURL/Lifestyle_Image_Web_1.png" /></div>
        <div><img class="lifeStyleImg" src="@ImageServerURL/Lifestyle_Image_Web_2.png" /></div>
        <div><img class="lifeStyleImg" src="@ImageServerURL/Lifestyle_Image_Web_3.png" /></div>
        <div><img class="lifeStyleImg" src="@ImageServerURL/Lifestyle_Image_Web_4.png" /></div>
    </div>
   

</div>

<div class="FAQContainer">
    <h2 class="desktopVersion">Frequently Asked Questions</h2>
    <h2 class="mobileVersion">FAQs</h2>
    <div class="FAQCardContainer">
        <div id="q1Card" class="FAQCard">
            <p id="q1" class="FAQText">Q. How Much Does Delivery Cost?</p>
            <p id="a1" class="FAQAnswerText">Standard delivery of 2-3 working days is free. Next-day delivery is available at a small cost. Read more <a href="https://gingerfox.co.uk/Help/DeliveryInformation">here</a>.</p>
        </div>
        <div id="q2Card" class="FAQCard">
            <p id="q2" class="FAQText">Q. What Is The Minimum Age For This Game?</p>
            <p id="a2" class="FAQAnswerText">We think this is a great game for players aged 8 years and over.</p>
        </div>
    </div>
    <div class="FAQCardContainer">
        <div id="q3Card" class="FAQCard">
            <p id="q3" class="FAQText">Q. When Will I Recieve My Item?</p>
            <p id="a3" class="FAQAnswerText">A tracking link will be emailed to you once your order has been shipped. <a href="https://gingerfox.co.uk/information/contact-us">Contact us</a> for more info.</p>
        </div>
        <div id="q4Card" class="FAQCard">
            <p id="q4" class="FAQText">Q. How Many People Can Play?</p>
            <p id="a4" class="FAQAnswerText">This is a great game for groups of 4-6 players.</p>
        </div>
    </div>
       
    
</div>


<link href="~/lib/Swiper/swiper-bundle.min.css" rel="stylesheet" asp-append-version="true" />
<script src="~/lib/Swiper/swiper-bundle.min.js" asp-append-version="true"></script>
<script src="~/js/index.js" asp-append-version="true"></script>

Pages/RedirectToGingerFox.cshtml
@page "/RedirectToGingerFox"
@model TraitorsMicroSite.Pages.RedirectToGingerFoxModel
@{
    Layout = null;
}
<head>
    <title>Redirecting to Ginger Fox</title>
    <link rel="icon" type="image/png" sizes="32x32" href="https://media.gingerfox.co.uk/TraitorsMicroSite/favicon-32x32.png">
</head>
<link href="~/css/redirecttogingerfox.css" rel="stylesheet" />
<script src="~/js/redirecttogingerfox.js"></script>
<div class="CenterContainer">
    <img class="loading" src="https://media.gingerfox.co.uk/GingerFoxHub/Site/Layout/Spinner.gif" />
    <p>Redirecting to</p>
    <img src="https://media.gingerfox.co.uk/GingerFoxHub/Site/Layout/Logos/GF_TITLE_AND_ROUND_LOGO_BLUE.svg" />
</div>
    

Pages/Shared/Components/CookieConsent/CookieConsent.cshtml
@{
    var CookieConsentTracking = Context.Request.Cookies["CookieConsentTracking"];
    var CookieConsent = Context.Request.Cookies["CookieConsent"];


}
@model IList<GingerFoxHub.Pages.Shared.Components.CookieConsent.CookieConsentViewComponent.CookieConsentData>




<link href="~/css/CookieConsent.css" rel="stylesheet" />
<script src="~/js/CookieConsent.js"></script>

@if (CookieConsent != "true")
{
    <div class="CookieTransparentBackground">
    </div>
    <div class="FixedCookiePopupContainer">
        <div class="CookiePopupContainer">
            <img class="bottomLeftCookie" src="https://media.gingerfox.co.uk/GingerFoxHub/Site/Layout/GF_HUB_COOKIE_POPUP.svg" />
            <div class="CookieMainContainer">
                <h4>Our Cookies</h4>
                <p>We use cookies to enhance your experience and for analytics on our site and third party sites. We may share your information with our advertising and analytics partners. Find out more about cookies by reading our <a href="/Information/PrivacyPolicy">Privacy Policy</a>. By clicking <b>"Allow All Cookies"</b> you agree to all of the above or you can click <b>"Cookie Settings"</b> to choose what cookies you are happy for us to use.</p>
                <button type="button" id="AcceptAllCookiesBtn" class="AcceptCookieBtn">Allow All Cookies</button>
                <button type="button" id="CookieSettingBtn" class="cookieSettingLink">Cookie Settings</button>
            </div>

            <div class="CookieSettingsContainer">

                <h4>Cookie Settings</h4>
                <label>
                    <input type="checkbox" id="EssentialCookies" checked="checked" disabled />
                    Necessary Essential Cookies
                </label>
                <p>These are cookies that are required to make the website functional. These can not be disabled as they are essential.</p>
                <label>
                    <input type="checkbox" id="TrackingCookies" />
                    Analytics/Advertising Cookies
                </label>
                <p>These cookies are used by our third party sites to help us with analytics. The following third party vendors we use are:</p>
                <ul>
                    @foreach (var cookieData in Model)
                    {
                        <li>@cookieData.Name</li>
                    }
                </ul>
                <button type="button" class="" id="SaveTrackingSettings">Save Settings</button>
            </div>
            <img class="TopRightCookie" src="https://media.gingerfox.co.uk/GingerFoxHub/Site/Layout/GF_HUB_COOKIE_POPUP.svg" />
        </div>

    </div>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TraitorsMicroSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TraitorsMicroSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TraitorsMicroSite - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/Shared/_TraitorsLayout.cshtml
<!DOCTYPE html>
@{
    string ImageServerURL = "https://media.gingerfox.co.uk/TraitorsMicroSite";
}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - The Traitors Card Game</title>
    <link href="https://use.typekit.net/thr0udu.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/TraitorsLayout.css" rel="stylesheet" asp-append-version="true" />
    <link rel="icon" type="image/png" sizes="32x32" href="@ImageServerURL/favicon-32x32.png">

    <script src="~/lib/jquery/jquery.js" asp-append-version="true"></script>
    <script src="https://sdks.shopifycdn.com/js-buy-sdk/v2/latest/index.umd.min.js" asp-append-version="true"></script>
    <script src="~/js/Shopify.js" asp-append-version="true"></script>
    <script src="~/js/TraitorsLayout.js" asp-append-version="true"></script>
    <script src="~/lib/js-cookie/js.cookie.js" asp-append-version="true"></script>
</head>


<body>
    <wrapper class="d-flex flex-column min-vh-100">

        <div class="headerContainer">

            <header>
                <div class="headerMainContainer container">
                    <a class="Logo" href="/">
                        <img src="@ImageServerURL/TRAITORS_LOGO.png" />
                    </a>
                    <ul class="Navigation">
                        <li class="InBoxBtn">What's In The Box?</li>
                        <li class="HowToPlayBtn">How To Play</li>
                        <li class="DetailsBtn">Details</li>
                        <li class="FAQsBtn">FAQs</li>
                    </ul>
                    <div id="BuyNowBtn" class="BuyNowBtn">Buy Now</div>
                    @*<button id="BuyNowBtn" class="BuyNowBtn" type="button">Buy Now</button>*@
                </div>
            </header>
            <div class="mobileNavContainer">
                <ul>
                    <li class="InBoxBtn">In The Box</li>
                    <li class="HowToPlayBtn">How To Play</li>
                    <li class="DetailsBtn">Details</li>
                    <li class="FAQsBtn">FAQs</li>
                </ul>
            </div>
        </div>



        <main role="main" id="main" class="flex-fill">
            @RenderBody()
        </main>

        <footer>
            <div class="footerContainer container">
                <img class="Logo2" src="@ImageServerURL/TRAITORS_LOGO.png" />
                @*<img class="Logo3" src="@ImageServerURL/WWTBAM_LOGO.png" />*@
                <ul class="footerList">
                    <li><a href="https://gingerfox.co.uk/information/contact-us">Contact Us</a></li>
                    <li><a href="https://gingerfox.co.uk/Help/DeliveryInformation">Delivery & Returns</a></li>
                    <li><a href="https://gingerfox.co.uk/Information/PrivacyPolicy">Privacy Policy</a></li>
                </ul>
                <ul class="footerList">
                    <li><a href="https://gingerfox.co.uk/Information/TermsAndConditions">Terms & Conditions</a></li>
                    <li><a href="https://gingerfox.co.uk/Information/EthicalEnvironmentalPolicy">Ethical & Environmental Policy</a></li>
                    <li><a href="https://gingerfox.co.uk/Information/Sustainability">Sustainability Promise</a></li>
                </ul>
               @* <div class="socialContainer">
                    <p>Follow Us</p>
                    <div class="socialIconContainer">
                        <a target="_blank" href="">
                            <img src="@ImageServerURL/TRAITORS_SOCIAL_SOCIAL_TW.png" />
                        </a>
                        <a href="">
                            <img src="@ImageServerURL/TRAITORS_SOCIAL_SOCIAL_FB.png" />
                        </a>
                        <a target="_blank" href="">
                            <img src="@ImageServerURL/TRAITORS_SOCIAL_SOCIAL_IG.png" />
                        </a>
                        <a target="_blank" href="">
                            <img src="@ImageServerURL/TRAITORS_SOCIAL_SOCIAL_YT.png" />
                        </a>
                        <a href="">
                            <img src="@ImageServerURL/TRAITORS_SOCIAL_SOCIAL_TT.png" />
                        </a>

                    </div>
                </div>*@
            </div>

        </footer>
        <div class="licensedLogoContainer container">
            <img class="licensedLogos desktopVersion" src="@ImageServerURL/LICENSED_LOGOS_WEB.png" />
            <img class="licensedLogos mobileVersion" src="@ImageServerURL/LICENSED_LOGOS_MOB.png" />
        </div>
        <div class="copyrightContainer container">
            <p>The Traitors &copy; idtv Film & Video Productions BV, RTL Netherlands and POSVIDEO, @DateTime.Now.Year. Licensed by All3Media International Ltd. Produced in the UK by Studio Lambert Ltd.</p>
            <p>&copy; @DateTime.Now.Year Ginger Fox Games Ltd.</p>
        </div>
    </wrapper>
    @await Component.InvokeAsync("CookieConsent", new
    {
    TrackingCookieNames = "Google Analytics"
    })
</body>

</html>